apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/truongnhatbui/techtrends
    targetRevision: HEAD
  syncPolicy: {}
